cam2image:
  ros__parameters:
    width: 480
    height: 240
    socket_ip: "172.28.208.1"
    socket_port: 9999
    remote_mode: true
    show_camera: true
    remote_timeout: 7
    history: "keep_last"
    durability: "volatile"
    reliability: "reliable"
    depth: 10
